export type EmployeeStatus = "active" | "inactive" | "resigned";
export type EmployeeRole = "employee" | "admin";

export type Employee = {
  id: string;
  employee_code: string;
  name: string;
  email: string;
  hire_date: string | null;
  resignation_date: string | null;
  status: EmployeeStatus;
  role: EmployeeRole;
  auth_user_id: string | null;
  created_at: string;
  updated_at: string;
};

export type PayrollRecord = {
  id: string;
  employee_id: string;
  payroll_month: string;
  attendance_days: number;
  holiday_attendance_days: number;
  paid_leave_days: number;
  absence_days: number;
  late_early_count: number;
  scheduled_work_hours: number;
  overtime_work_hours: number;
  holiday_work_hours: number;
  late_night_hours: number;
  late_early_hours: number;
  base_salary: number;
  overtime_pay: number;
  allowances: number;
  holiday_pay: number;
  late_night_pay: number;
  taxable_transportation_allowance: number;
  non_taxable_transportation_allowance: number;
  payment_total: number;
  transportation_expense: number;
  health_insurance: number;
  pension_insurance: number;
  employment_insurance: number;
  nursing_care_insurance: number;
  income_tax: number;
  resident_tax: number;
  child_care_support: number;
  other_deductions: number;
  total_deductions: number;
  social_insurance_total: number;
  taxable_amount: number;
  bank_transfer_amount: number;
  net_pay: number;
  created_at: string;
  updated_at: string;
};
